### ISSUE TITLE
Stuck on "Joining world..." screen when launching any game, solo or server

### ISSUE THREAD

**Issue by Lastic0t** [YassaaaTU/ALOE#5] opened 2023-03-13 22:05 UTC
Latest version of the modpack provided, dowloaded off of CurseForge app.

So I don't know if anyone's still working on this, seeing when were the last updates but i'll try this anyways.
We wanted to try this modpack with some friends on a server. The server itself seems to have no issues for now,
but we can't figure out a way to actually play the game, as said in the title, the game both on single and multi - player doesn't let you past the "Joining world..." screen with a weird fade effect.

![image](https://user-images.githubusercontent.com/127797523/224841732-28e5e51d-1274-4e4c-b49e-77071b455a1f.png)

(As this was on the server, I tried killing my character via the console)

The game is running in the background as you can see the particles and hear all the game sounds, but nothing else
I didn't know what file would be interesting to provide so ask anything, we're actually quite exited about this modpack, would be a shame if nothing was possible to fix this.

**Comment by YassaaaTU** [comment] 2023-03-14 08:26
Hey thanks for wanting to play my modpack it really does make me happy!

I will get back to you about this issue and try to resolve it when I'm back from work 😃 

I'm also currently not working on this modpack anymore I'm trying to make a nicer 1.19.2 version still not ready to be played or uploaded yet tho. But I kinda have hard time managing time because of work and uni

**Comment by YassaaaTU** [comment] 2023-03-14 08:28
Also if I remember correctly I'm at the time of creating this modpack there was an issue with one of the mods that caused what you are experiencing. And I think it got resolved with an update but I'm not sure.

So if u don't want to wait then maybe you can try copying the modpack and removing mods to see which one caused the error. (Remove half of the mods and start, if error resides then remove half of the mods again and so on). Then maybe try updating the mod or checking it's channeling to see if it got resolved

**Comment by Lastic0t** [comment] 2023-03-14 14:59
Hey, thank you for answering that quick :)

I tried removing one - I'd have to double check the name, but it was one that supposedly needed an update - didn't change anything. Just wanted to confirm that we tired on every single one of our pcs and same exact bug for each of us.

I wanted to ask you about those JVM arguments that you included in the CurseForge description of the modpack. Could those be helpful to resolve this issue or purely performance related ? And also would there be any way to see wich one of the mods could cause any issue ? Not that I'm not a fan of checking every single one of the 400ish mods one by one but y'know... :)

Sorry if that doesn't make sense, I'm really not the best when it comes to makin computers work the way they should ^^

**Comment by YassaaaTU** [comment] 2023-03-14 22:25
I think it was Danny's Expansion? but not I'm entirely sure. 
I wouldn't recommend playing this pack but if you really want to, I can try to see what's the cause in the weekend.

**Closed** 2023-04-18 10:18 UTC
Labels: bug, wontfix
